CREATE TABLE recipe_ingredients (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ingredient TEXT NOT NULL,
  unit TEXT NOT NULL,
  amount numeric NOT NULL,
  recipe_id INTEGER REFERENCES dinner_recipes(id) NOT NULL
);