CREATE TABLE dinner_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  first_name TEXT NOT NULL,
  password TEXT NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  date_modified TIMESTAMPTZ
);

ALTER TABLE dinner_recipes
  ADD COLUMN
    user_id INTEGER REFERENCES dinner_users(id) ON DELETE SET NULL;

ALTER TABLE dinner_restaurants
  ADD COLUMN
    user_id INTEGER REFERENCES dinner_users(id) ON DELETE SET NULL;