BEGIN;

TRUNCATE
  dinner_restaurants,
  dinner_recipes,
  recipe_ingredients
  RESTART IDENTITY CASCADE; 

INSERT INTO dinner_restaurants (title, phone_number, web_url, style, restaurant_address, user_id)
VALUES
('Taco Bell', '(704) 525-3661', 'https://locations.tacobell.com/nc/charlotte/2405-south-blvd.html?utm_source=yext&utm_campaign=googlelistings&utm_medium=referral&utm_term=005671&utm_content=website&y_source=1_MzkxNjkwNy03MTUtbG9jYXRpb24uZ29vZ2xlX3dlYnNpdGVfb3ZlcnJpZGU%3D', 'chain', '2405 South Blvd, Charlotte, NC 28203', 1),
('Popeyes Louisiana Kitchen', '(704) 394-8243', 'https://www.popeyes.com/store-locator/store/restaurant_84795', 'chain', '3318 Wilkinson Blvd, Charlotte, NC 28208', 1),
('Shake Shack', '(980) 265-3188', 'https://www.shakeshack.com/location/park-road-charlotte-nc/?utm_source=G&utm_medium=local&utm_campaign=google-local', 'chain', '1605 E Woodlawn Rd, Charlotte, NC 28209', 1),
('Five Guys', '(704) 333-4450', 'http://www.fiveguys.com/', 'chain', ' 2810 South Blvd Unit A, Charlotte, NC 28209', null),
('Papa John''s Pizza', '(704) 522-7272', 'https://locations.papajohns.com/united-states/nc/28217/charlotte/4820-south-blvd?utm_source=gmb&utm_medium=organic&y_source=1_MTA2OTI1MDYtNzE1LWxvY2F0aW9uLmdvb2dsZV93ZWJzaXRlX292ZXJyaWRl', 'chain', '4820 South Blvd, Charlotte, NC 28217', null),
('Panera Bread', '(980) 215-6496', 'https://locations.panerabread.com/nc/charlotte/3625-city-park-dr.html?utm_medium=display-ad&utm_source=paid-digital&utm_campaign=yext&utm_content=local-search', 'chain', '3625 City Park Dr, Charlotte, NC 28217', null),
('Domino''s Pizza', '(704) 527-7892', 'https://www.dominos.com/en/?utm_source=google&utm_medium=loclist&utm_campaign=localmaps', 'chain', '4755 South Blvd, Charlotte, NC 28217', null),
('Chick-Fil-A', '(704) 665-6371', 'https://www.chick-fil-a.com/southend', 'chain', '3015 South Blvd, Charlotte, NC 28209', 1),
('McDonald''s', '(704) 523-6334', 'https://www.mcdonalds.com/us/en-us/location/NC/CHARLOTTE/4440-S-TRYON-ST/6788.html?cid=RF:YXT:GMB::Clicks', 'chain', '4440 S Tryon St, Charlotte, NC 28210', null),
('Little Village Grill', '(704) 347-2184', 'https://www.facebook.com/littlevillagegrill/', 'local', '710 W Trade St, Charlotte, NC 28202', 1),
('VANA', '(980) 819-5913', 'http://vanarestaurant.com/', 'local', '1440 S Tryon St Suite 100, Charlotte, NC 28203', null),
('Mama Ricotta''s', '(704) 343-0148', 'https://www.mamaricottas.com/', 'local', '601 S Kings Dr AA, Charlotte, NC 28204', null),
('NoDa Bodega', '(704) 375-8704', 'http://www.nodabodega.com/', 'local', '1200 E 36th St, Charlotte, NC 28205', null),
('Bao and Broth', '(704) 625-2269', 'http://www.baoandbroth.com/', 'local', '1115 North Brevard Street, Suit #5, Charlotte, NC 28206', null),
('Common Market SouthEnd', '(980) 207-3187', 'https://commonmarketisgood.com/south-end/', 'local', '235 W Tremont Ave, Charlotte, NC 28203', null),
('Rhino Market & Deli', '(704) 375-2036', 'http://rhinomarket.com/', 'local', '1500 W Morehead St Ste E, Charlotte, NC 28208', 1),
('Futo Buta', '(704) 376-8400', 'https://futobuta.com/', 'local', '222 E Bland St, Charlotte, NC 28203', null),
('Papi Queso', '(704) 579-1779', 'http://papiquesotruck.com/', 'local', '1115 N Brevard St, Charlotte , NC 28206', null);

INSERT INTO dinner_recipes (user_id, title, content)
VALUES
  (1, 'Herbed Oyster Mushroom Steak', 'Preheat oven to 375 degrees. Zest and juice lemon into a medium bowl. Add chopped parsley, scallion bulbs, olive oil, onion powder, and garlic powder. Whisk to combine. Add oyster mushrooms to the bowl with the marinade, toss to coat mushrooms, and set aside. Mushrooms can marinate for up to 24 hours in the refrigerator. Heat a medium cast iron pan over medium-high heat. Add olive oil to fully coat the bottom of pan. Remove mushrooms from the marinade and place in pan to sear (TIP: place a second pan on top of the mushrooms to weigh them down and create a more even sear). Cook mushrooms for about 5 minutes on each side. Remove top pan (if used) and place mushrooms in oven for 5-7 minutes to finish cooking and ensure crisping.'),
  (1, 'Kohlrabi Schniztel', 'Bring a medium sized pot of salted water to a boil. While waiting for the water to boil use a vegetable peeler and remove the outer layer of the kohlrabi, discarding the peels. Cut the Kohlrabi into ½ inch sized slices and boil for 6-8 minutes. Remove the kohlrabi from the pot and set it aside to cool. (This process can be done the day before making the final dish) To prepare the egg wash: crack the egg into a small bowl and whisk with 1 tablespoon of water. Add the smoked paprika, salt, and (optional) poultry seasoning and whisk to combine. To prepare vegan option egg wash: in a small bowl, mix 0.25 cup all purpose flour with 1/3 cup water. Add salt, smoked paprika, and (optional) poultry seasoning and whisk until a smooth a consistency is reached. Add all of the ingredients for the breading into a separate medium sized bowl. To bread your kohlrabi, dip pieces into your wash and then into your dredge. Press the kohlrabi firmly in the breading on all sides to make sure the breading adheres. In a medium sized frying pan, heat 1/8 cup of oil over medium heat. Fry breaded kohlrabi for 5 minutes on each side. Remove from the pan once done, season with salt and pepper, and place on a pan with a napkin to absorb any residual oil. Enjoy schnitzel over mashed potatoes, on a Duke''s Bread brioche hamburger bun, or on top of a fresh Fair Share spring mix salad!'),
  (1, 'Teriyaki Marinated Eggplant', 'Whisk all marinade ingredients in a medium bowl thoroughly to dissolve the brown sugar. Add cut eggplant to your bowl with the teriyaki marinade. Leave eggplant in the marinade for 1 hour. While the eggplant is marinating, heat a large pot of salted water to a boil. Blanch the cut beans for 2-3 minutes: remove the beans using a strainer and place into ice water for 2-3 minutes until the cooking stops. Remove from the water, dry, and set aside. Once the eggplant is done marinating, heat 1 tbsp of oil in a medium non-stick pan over medium heat. Remove eggplant from the marinade and brown, turning to cook all sides, for 4-5 minutes. Remove the eggplant, then add onions and long beans and saute for 2-3 minutes. Add the eggplant back to the pan with any remaining marinade, and let simmer for 2-3 minutes. Serve over white or brown rice, garnish with scallion greens and sesame seeds.'),
  (null, 'Turkey and Andouille Smoked Sausage Gumbo', 'Combine 0.5 cup flour and 0.5 tsp each of salt, garlic powder, and red pepper in a small bowl. Sprinkle salt, garlic, and red pepper on your leftover turkey (to taste) and set aside. In a large heavy skillet, heat 0.5 cup of oil. Fry the andouille until brown on all sides and the meat is cooked (about 5 minutes). Remove from the pan and drain on paper towels. Place the pan over high heat. Using a long-handled metal whisk, gradually stir in the flour mixture. Cook, whisking constantly until the roux is rust-colored and the consistency of grits or oatmeal (you may need extra flour). It usually takes 4 to 5 minutes. Remove from the heat as soon as it’s the right color and consistency, and immediately add the vegetables, stirring constantly to cool the roux down. Return the pan to low heat and cook until the vegetables are soft, about 5 minutes, stirring constantly and scraping the pan bottom. While the roux and vegetables cook, bring the stock to a boil in a large soup pot. Add the roux to the boiling stock one spoonful at a time, stirring until dissolved before adding more. Return your stock mixture to a boil before reducing the heat to a simmer. Stir in the andouille, garlic, and turkey. Simmer uncovered for about 30 minutes, stirring and scraping the pan bottom often. Serve immediately with plenty of rice. We recommend Carolina Gold Rice for a delicious local option. This recipe freezes well! Recipe courtesy of Erin Bradley, adapted by Chef Matt Martin.'),
  (null, 'Kabocha Squash Bisque', 'Preheat your oven to 400 degrees. Cut the kabocha squash in half, scrape out the seeds, and place the squash cut side down on a sheet pan lined with parchment paper. Bake squash for 1-1.5 hours until it is tender and develops some good color. When your squash is fully roasted, remove from the oven and let it cool until you can scoop out the flesh. Heat a pot over medium low heat and add the oil. Add the onion, celery, pepper, carrot, and garlic, and sauté for 10 minutes. Add the roasted squash, apples, tomatoes, herbs, and maple syrup. Let this reduce for 5 minutes. Add the stock and let simmer for 30 minutes. Remove from the heat and purée in a high speed blender, being careful to fill the blender no more than halfway and to leave a vent for steam to escape. Season with salt and pepper. Serve garnished with diced apples, crème fraîche, or thyme- or all three!'),
  (null, 'Grilled Peach and Heirloom Tomato Salad', 'Preheat your oven to 375 degrees. Toss your almonds with 1 teaspoon of olive oil, sprinkle with salt and pepper and toast in the oven for 7-10 minutes. Combine all of your dressing ingredients into a small bowl and whisk together, taste and adjust seasonings as needed. To grill your peaches brush peaches with oil and place on a greased grill over medium-high heat; close the lid and grill, turning once, until peaches are softened and grill-marked, about 6 minutes To assemble, place grilled peaches and quartered tomatoes in an alternating pattern on a plate, top with your herbs, toasted nuts, and cheese and finish by carefully pouring your dressing over the top. Finish this dish with a heavy pinch of salt and enjoy right away.'),
  (null, 'Koginut Squash and Apple Salad', 'Preheat oven to 375 degrees. Cut squash in half, remove the seeds and place on a baking sheet cut side down. Rub the outside of the squash with a small amount of oil and season with salt and pepper. Roast for 40-55 minutes or until a paring knife can pierce the squash with no resistance. While the squash is roasting, prepare your vinaigrette. Combine vinegar, mustard, salt, and syrup in a small bowl. Slowly whisk in the olive oil until a creamy texture is achieved. Season with salt and pepper. Once the squash has finished roasting, let it cool to room temperature. Cut a few slices of squash and place it on your plate, them dress the lettuce with the vinaigrette and place that on the squash. Finish the salad by adding diced apples, dried fruit, seeds/nuts, and some soft cheese of your choice. This is a great template to create a flavorful fall salad with what you have on hand!'),
  (null, 'Warm Green Bean and Peach Salad', 'Bring a medium sized pot of water up to boil and add a pinch of salt. In a separate bowl add some water and ice together to make an ice bath. Clean the ends off of the green beans with a pairing knife. When the water is boiling put your green beans in for 2-3 minutes. Remove from boiling water immediately and place in the ice bath. Strain the beans from the water and set aside. Cut your cherry tomatoes in half and remove the pit from your peach. Cut your peaches into slices and set aside. In a medium sized pan over medium heat melt your butter and add your pecans. Cook your pecans over medium heat for 3-4 minutes or until fragrant. Next add your brown sugar, maple syrup, stock, cherry tomatoes and peaches. Cook together until the peaches are warm and there is a small sauce sticking to the beans. Season with salt and pepper and enjoy as a nice summer side!'),
  (null, 'Yellow Tomato Gazpacho', 'Roughly dice all of the prepped vegetables- don''t worry about knife cuts, everything will be pureed. Add the vegetables, bread, and white balsamic vinegar to the base of a high speed blender (a regular blender or immersion blender will work, too!). Start the blender on low speed. While the blender is running, slowly pour your olive oil through the top of the blender. As you add the oil, your soup will start to thicken. The soup should be very smooth once all of the oil has been added. Remove from the blender and season with additional salt, pepper, and hot sauce as needed. Serve cold, garnished with a drizzle of olive oil and chopped herbs (parsley, basil, or chervil all work well).');

INSERT INTO recipe_ingredients (recipe_id, ingredient, unit, amount)
VALUES
  (1, 'Lemon, zested & juiced', 'each', 1),
  (1, 'Olive oil', 'cup', 0.33),
  (1, 'Parsley, chopped', 'tbsp', 2),
  (1, 'Scallions, chopped & greens reserved', 'each', 4),
  (1, 'Garlic Powder', 'tbsp', 0.5),
  (1, 'Onion Powder', 'tbsp', 0.5),
  (1, 'Oyster Mushrooms', 'lb', 1),
  (2, 'Medium Kohlrabi', 'head', 1),
  (2, 'Egg (Vegan option: 0.25 cup AP Flour + 1/3 cup water)', 'tsp', 0.5),
  (2, 'Smoked Paprika', 'tsp', 0.5),
  (2, 'Salt', 'tsp', 0.5),
  (2, 'Poultry Seasoning, optional', 'tsp', 1),
  (2, 'Bread Crumbs', 'cup', 0.5),
  (2, 'Smoked Paprika', 'tsp', 0.5),
  (2, 'Salt', 'tsp', 0.5),
  (2, 'Crushed Oats', 'tbsp', 1),
  (2, 'Oil', 'tbsp', 2),
  (3, 'Medium Eggplant, cut into 0.5 inch chunks', 'each', 1),
  (3, 'Long Beans, cut into 2-3 inch pieces', 'oz', 8),
  (3, 'White Onion, medium diced', 'each', 0.5),
  (3, 'Scallion, sliced on a bias, greens reserved for garnish', 'each', 1),
  (3, 'Sesame Seeds, for garnish', 'tbsp', 1),
  (3, 'Soy Sauce', 'cup', 0.5),
  (3, 'Mirin', 'cup', 0.25),
  (3, 'Rice Wine Vinegar', 'tbsp', 1),
  (3, 'Brown Sugar', 'tbsp', 1.5),
  (3, 'Ginger, 2 tbsp grated & 2 tbsp minced', 'tbsp', 4),
  (4, 'All Purpose Flour', 'cup', 0.5),
  (4, 'Garlic Powder, more to taste', 'tsp', 0.5),
  (4, 'Ground Red Pepper, more to taste', 'tsp', 0.5),
  (4, 'Salt, more to taste', 'tsp', 0.5),
  (4, 'Leftover Turkey', 'lb', 2),
  (4, 'Oil', 'cup', 0.5),
  (4, 'Andouille Sausage, chopped', 'lb', 0.5),
  (4, 'Onion, chopped', 'each', 1),
  (4, 'Green Pepper, chopped', 'cup', 1.5),
  (4, 'Celery, chopped', 'cup', 1.25),
  (4, 'Chicken Stock', 'cup', 7),
  (4, 'Garlic, minced', 'tsp', 1),
  (5, 'KabochaSquash', 'each', 1),
  (5, 'Onion, diced', 'each', 1),
  (5, 'Celery, diced', 'each', 2),
  (5, 'Red Bell Pepper, diced', 'each', 1),
  (5, 'Carrot, peeled & diced', 'each', 1),
  (5, 'Garlic, minced', 'clove', 1),
  (5, 'Apple, cored & diced', 'each', 1),
  (5, 'Tomato, diced', 'each', 1),
  (5, 'Thyme, chopped', 'oz', 1),
  (5, 'Rosemary, chopped', 'oz', 1),
  (5, 'Oil', 'oz', 2),
  (5, 'Maple Syrup', 'oz', 2),
  (5, 'Stock, Vegetable or Chicken', 'gal', 0.5),
  (5, 'Salt & Pepper', 'to taste ', 0),
  (6, 'Peaches, pitted & sliced into quarters', 'each', 2),
  (6, 'Heirloom Tomato, quartered', 'each', 1),
  (6, 'Basil, torn', 'cup', 0.25),
  (6, 'Parsley, chopped', 'tbsp', 2),
  (6, 'Almonds, toasted', 'oz', 1),
  (6, 'Soft Cheese (Goat/Mozz/Vegan Ricotta)', 'oz', 2),
  (6, 'White Balsamic Vinegar', 'tbsp', 2),
  (6, 'Olive Oil', 'tbsp', 3),
  (6, 'Grainy Mustard', 'tsp', 2),
  (6, 'Honey, or Agave', 'tsp', 1),
  (6, 'Red Pepper Flakes', 'tsp', 0.25),
  (6, 'Salt & Pepper', 'tsp', 0.25),
  (7, 'Koginut Squash', 'each', 1),
  (7, 'Apple, diced', 'each', 1),
  (7, 'Dried Fruit (cranberries, raisins, etc.)', 'oz', 2),
  (7, 'Nuts or Seeds', 'oz', 1),
  (7, 'Spring Mix', 'oz', 4),
  (7, 'Soft or Vegan Cheese', 'oz', 1),
  (7, 'Apple Cider Vinegar', 'cup', 0.25),
  (7, 'Dijon Mustard', 'tsp', 1),
  (7, 'Salt', 'tsp', 0.5),
  (7, 'Maple Syrup', 'tbsp', 1.5),
  (7, 'Olive Oil', 'tbsp', 5),
  (8, 'Green Beans', 'oz', 8),
  (8, 'Medium Peach', 'each', 1),
  (8, 'Cherry Tomatoes', 'oz', 3),
  (8, 'Pecans', 'oz', 2),
  (8, 'Vegetable Stock', 'oz', 1),
  (8, 'Butter, or Vegan Alternate', 'tbsp', 1),
  (8, 'Maple Syrup', 'tbsp', 0.5),
  (8, 'Brown Sugar', 'tbsp', 0.5),
  (8, 'Salt & Pepper', 'to tase', 0),
  (9, 'Yellow Tomato', 'lb', 2),
  (9, 'Carrot, peeled', 'each', 1),
  (9, 'Red Bell Pepper, cored & deseeded', 'each', 1),
  (9, 'Cucumber, peeled & deseeded', 'each', 1),
  (9, 'Onion, cored', 'each', 1),
  (9, 'Garlic', 'clove', 1),
  (9, 'White Bread, toasted medium', 'slice', 1),
  (9, 'White Balsamic Vinegar', 'tsp', 2),
  (9, 'Olive Oil', 'cup', 0.5),
  (9, 'Tabasco', 'dash', 1);

COMMIT;